name: leboncoin
options:
  deploymentTarget:
    iOS: 14.0
settings:
  USER_DEFINED_COMMERCIAL_VERSION: "1.0.0"
  USER_DEFINED_VERSION: "1"
targets:
  leboncoin:
    scheme: {}
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: leboncoin/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.leboncoin.app
      BUILD_LIBRARY_FOR_DISTRIBUTION: true
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
    info:
      path: leboncoin/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        CFBundleDisplayName: leboncoin
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
    sources:
      - path: leboncoin
